name: Translation Check

on:
  workflow_dispatch:
  push:
    branches:
      - main

jobs:
  check-translations:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-node@v4
        with:
          node-version: "18.16.0"
          cache: "npm"
      - run: npm ci
      - run: npm run locale --update-locales
      - run: |
          CHANGES=$(git diff --name-only)
          if [ -z "$CHANGES" ]
          then
            echo "No translations needed"
          else
            echo "The following files need translations:"
            echo $CHANGES
            exit 1
          fi
